public class charDataType {
    public static void main(String args[]) {
        char ch1;
        ch1 = 'X';
        System.out.println("ch1 contains " + ch1);
        ch1++; // increment ch1
        System.out.println("ch1 is now " + ch1);
        }
       }
       /* 
       The output generated by this program is shown here:
        ch1 contains X
        ch1 is now Y
       In the program, ch1 is first given the value X. Next, ch1 is incremented. This results in ch1
       containing Y, the next character in the ASCII (and Unicode) sequence.
       
       NOTE In the formal specification for Java, char is referred to as an integral type, which means that it is in the same general category as int, short, long, and byte. However, because its principal use is for 
       representing Unicode characters, char is commonly considered to be in a category of its own.
*/
